In [1]:
import numpy as np

In [2]:
c = np.array([[10, 11, 12], [20, 21, 22]])

In [3]:
c

array([[10, 11, 12],
       [20, 21, 22]])

In [4]:
c.ndim

2

In [5]:
c.shape

(2, 3)

In [6]:
c

array([[10, 11, 12],
       [20, 21, 22]])

In [7]:
c.size

6

In [9]:
c.dtype

dtype('int32')

In [10]:
c.nbytes

24

In [11]:
a = np.arange(25)

In [12]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
a = a.reshape(5,5)

In [14]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
a[-1, :]

array([20, 21, 22, 23, 24])

In [17]:
a[:, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [19]:
a[1::2, :3:2]

array([[ 5,  7],
       [15, 17]])